network-monitor-master/network_monitor/discover/urls.py
from django.urls import path
from discover import views

urlpatterns = [
    path('', views.Discover.as_view(), name="discover-device"),
    path('add/manual/', views.AddManual.as_view(), name="device-add-manual"),
    path('add/discover/', views.AddDiscover.as_view(), name="device-add-discover")
]

network-monitor-master/network_monitor/network_monitor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('accounts/', include('authen.urls')),
    path('discover/', include('discover.urls')),
    path('device/', include('device.urls')),
    path('task/', include('task.urls')),
    path('setting/', include('setting.urls')),
    path('report/', include('report.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

network-monitor-master/network_monitor/task/urls.py
from django.urls import path
from .views import list_task

urlpatterns = [
    path('', list_task, name='list-task'),
]

network-monitor-master/network_monitor/device/models.py
import re

from djongo import models

from .snmp_utils import oid_product_cisco


class Neighbor(models.Model):
    class Meta:
        abstract = True

    source = models.CharField()  # CDP or LLDP or Other.
    local_if_index = models.IntegerField(null=True)

    remote_ip_address = models.CharField()
    remote_version = models.CharField()  # Aka sysDescription
    remote_hostname = models.CharField()
    remote_port_description = models.CharField()
    remote_chassis_id = models.CharField(null=True)


class Hardware(models.Model):
    class Meta:
        abstract = True

    description = models.CharField()
    state = models.IntegerField()
    value = models.IntegerField()
    threshold = models.IntegerField()

    def __str__(self):
        return "{} is {}".format(self.description, self.value)


class Temperature(models.Model):
    class Meta:
        abstract = True

    description = models.CharField()
    state = models.IntegerField()
    value = models.IntegerField()
    threshold = models.IntegerField()

    def __str__(self):
        return "{} is {}".format(self.description, self.value)


class Fans(models.Model):
    class Meta:
        abstract = True

    description = models.CharField()
    state = models.IntegerField()


class PowerSupply(models.Model):
    class Meta:
        abstract = True

    description = models.CharField()
    state = models.IntegerField()


class DeviceInterface(models.Model):
    class Meta:
        abstract = True

    UP = 1
    DOWN = 2
    TESTING = 3

    STATUS_TEXT = {
        UP: 'UP',
        DOWN: 'DOWN',
        TESTING: 'TESTING'
    }

    previous_fetch_time = models.DateTimeField()
    fetch_time = models.DateTimeField()

    previous_in_usage = models.FloatField(default=0.0)
    previous_out_usage = models.FloatField(default=0.0)
    in_usage = models.FloatField(default=0.0)
    out_usage = models.FloatField(default=0.0)

    status = models.IntegerField(null=True)
    admin_status = models.IntegerField(null=True)
    oper_status = models.IntegerField(null=True)

    description = models.CharField(max_length=255)

    alias = models.CharField(max_length=255)

    speed = models.IntegerField(default=0)

    # use for SNMP
    oid_index = models.IntegerField()

    def in_usage_bps(self):
        if self.speed <= 0:
            return 0
        in_time = self.fetch_time - self.previous_fetch_time
        in_time = in_time.seconds + (in_time.microseconds / 1000000)
        return ((self.in_usage - self.previous_in_usage) * 8) / in_time

    def out_usage_bps(self):
        if self.speed <= 0:
            return 0
        in_time = self.fetch_time - self.previous_fetch_time
        in_time = in_time.seconds + (in_time.microseconds / 1000000)
        return ((self.out_usage - self.previous_out_usage) * 8) / in_time

    def in_usage_percent(self):
        if self.speed <= 0:
            return '{:.2f}'.format(0.0)
        in_time = self.fetch_time - self.previous_fetch_time
        in_time = in_time.seconds + (in_time.microseconds / 1000000)
        percent = (((self.in_usage - self.previous_in_usage) * 8) / (
                in_time * self.speed)) * 100
        print(self.description, self.in_usage, self.previous_in_usage, in_time,
              self.speed)
        return "{percent:.{point:}f}".format(percent=percent, point=2)

    def out_usage_percent(self):
        if self.speed <= 0:
            return '{:.2f}'.format(0.0)
        in_time = self.fetch_time - self.previous_fetch_time
        in_time = in_time.seconds + (in_time.microseconds / 1000000)
        percent = (((self.out_usage - self.previous_out_usage) * 8) / (
                in_time * self.speed)) * 100
        return "{percent:.{point:}f}".format(percent=percent, point=2)

    def __str__(self):
        return str(self.oid_index)


class Device(models.Model):
    ip_address = models.CharField(max_length=255, unique=True)
    netmask = models.CharField(max_length=255, null=True)  # Netmask ipAdEntNetMask
    hostname = models.CharField(max_length=255, blank=True)
    sitename = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    object_id = models.CharField(max_length=255, blank=True)
    uptime = models.IntegerField(default=-1)

    status = models.BooleanField(default=False)

    snmp_version = models.CharField(max_length=10, blank=True)
    snmp_community = models.CharField(max_length=255, blank=True)
    snmp_username = models.CharField(max_length=255, blank=True)
    snmp_password = models.CharField(max_length=255, blank=True)
    # Polling interval
    snmp_polling_local_interval = models.BooleanField(default=False)
    snmp_polling_interval = models.IntegerField(default=0)

    # Status
    ping_status = models.BooleanField(default=False)
    snmp_status = models.BooleanField(default=False)

    # Interfaces
    interfaces = models.ArrayModelField(
        model_container=DeviceInterface,
        default=[]
    )

    # Neighbor
    neighbor = models.ArrayModelField(
        model_container=Neighbor,
        default=[]
    )

    # Fans
    fans = models.ArrayModelField(
        model_container=Fans,
        default=[]
    )

    # PowerSupply
    power_supplies = models.ArrayModelField(
        model_container=PowerSupply,
        default=[]
    )

    # Temperature
    temperature = models.ArrayModelField(
        model_container=Temperature,
        default=[]
    )

    # Hardware
    hardware = models.ArrayModelField(
        model_container=Hardware,
        default=[],
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.hardware_status = None

    def get_manufacturer(self):
        if 'cisco' in self.description:
            return 'cisco'

    def get_version(self):
        pass

    def is_down(self):
        return not self.ping_status or not self.snmp_status or not self.status_ok()

    def status_ok(self):
        if self.hardware_status is not None:
            return self.hardware_status

        if not self.ping_status or not self.snmp_status:
            self.hardware_status = False
            return False

        for fan in self.fans:
            if not fan.state:
                self.hardware_status = False
                return False

        for psu in self.power_supplies:
            if not psu.state:
                self.hardware_status = False
                return False

        for t in self.temperature:
            if not t.state:
                self.hardware_status = False
                return False

        for h in self.hardware:
            if not h.state:
                self.hardware_status = False
                return False

        self.hardware_status = True
        return True

    @property
    def is_router(self):
        if not self.object_id:
            return False
        object_name = oid_product_cisco.get(self.object_id.strip('.'))
        if not object_name:
            return False

        test = re.compile(r'cisco(ASR)?([0-9]+)')
        if test.match(object_name):
            return True

        return False

    @property
    def is_switch(self):
        if not self.object_id:
            return False
        object_name = oid_product_cisco.get(self.object_id.strip('.'))
        if not object_name:
            return False

        if object_name.startswith('catalyst') or object_name.startswith('catWs'):
            return True

        test = re.compile(r'(cat)?(ciscoMe)?([0-9]+)')
        if test.match(object_name):
            return True

        return False


class DeviceInterfaceStatusLog(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

    description = models.CharField(max_length=255)

    from_status = models.IntegerField(default=0)
    to_status = models.IntegerField(default=0)
    oid_index = models.IntegerField()

    created_at = models.DateTimeField()


class DeviceInterfaceStatusHistory(models.Model):
    """
    This collecting device status history for status is not UP
    """
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

    description = models.CharField(max_length=255)

    # ip_address = models.CharField(max_length=255)
    # hostname = models.CharField(max_length=255, blank=True)
    # sitename = models.CharField(max_length=255, blank=True)
    # object_id = models.CharField(max_length=255, blank=True)

    status = models.IntegerField()

    start_at = models.DateTimeField(null=True)
    end_at = models.DateTimeField(null=True)

    created_at = models.DateTimeField()


class DeviceStatusHistory(models.Model):
    """
    This collecting device status history for status is not UP
    """
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

    ip_address = models.CharField(max_length=255)
    hostname = models.CharField(max_length=255, blank=True)
    sitename = models.CharField(max_length=255, blank=True)
    object_id = models.CharField(max_length=255, blank=True)

    status = models.IntegerField()

    start_at = models.DateTimeField(null=True)
    end_at = models.DateTimeField(null=True)

    created_at = models.DateTimeField()


class CpuHistory(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

    values = models.DictField(default={})

    num_samples = models.IntegerField(default=0)
    total_samples = models.FloatField(default=0.0)

    timestamp_hour = models.DateTimeField()


class DeviceObjectId(models.Model):
    object_id = models.CharField(max_length=255, primary_key=True)
    manufacturer = models.CharField(max_length=255, blank=True)
    device_type = models.CharField(max_length=255)
    device_type_name = models.CharField(max_length=255, blank=True)

network-monitor-master/network_monitor/report/models.py
from djongo import models


class Settings(models.Model):
    key = models.CharField(primary_key=True, unique=True, max_length=255)
    value = models.CharField(null=True, max_length=255)
    value_date = models.DateTimeField(null=True)

network-monitor-master/network_monitor/discover/views.py
import json

import netaddr
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from device.models import Device
from discover.forms import AddManualForm, AddDiscoverForm
from .tasks import ping_host


class Discover(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'device.add_device'

    def get(self, request):
        return render(request, "discover/discover.html")

    def post(self, request):
        network_str = request.POST.get('network')
        if not network_str:
            messages.warning(request, 'Network is empty.')
            return redirect('discover-device')

        hosts = []

        if "-" in network_str:
            start_ip, end_ip = network_str.split('-')
            start_ip = start_ip.strip()
            end_ip = end_ip.strip()
            network = netaddr.IPRange(start_ip, end_ip)
            for host in network:
                hosts.append(str(host))
        else:
            try:
                network = netaddr.IPNetwork(network_str)
            except Exception:
                messages.warning(request, 'Network {} is invalid.')
                return redirect('discover-device')

            for host in network.iter_hosts():
                hosts.append(str(host))

        class NetaddrEncoder(json.JSONEncoder):
            def default(self, o):
                if isinstance(o, netaddr.IPAddress):
                    return str(o)
                return super().default()

        result = ping_host.apply_async(args=(hosts, 256))
        result_output = result.wait(timeout=None, interval=0.1)

        # Convert to list of object(dict)
        # final_result = []
        # for ip, status in result_output.items():
        #     final_result.append({'ip': ip, 'status': status})

        scan_result = json.dumps(result_output, cls=NetaddrEncoder)
        return render(request, "discover/discover.html", {'add_type': 'discover', 'scan_result': scan_result})


class AddManual(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'device.add_device'

    def post(self, request):
        form = AddManualForm(request.POST)
        if form.is_valid():
            Device.objects.update_or_create(
                ip_address=form.cleaned_data['ip_address'],
                defaults={
                    'snmp_version': form.cleaned_data['snmp_version'],
                    'snmp_username': form.cleaned_data['snmp_username'],
                    'snmp_password': form.cleaned_data['snmp_password'],
                    'snmp_community': form.cleaned_data['snmp_community'],
                    'sitename': form.cleaned_data['sitename']
                }
            )

        messages.success(request, 'Added a device successfully.')
        return redirect('list-device')


class AddDiscover(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'device.add_device'

    def post(self, request):
        form = AddDiscoverForm(request.POST)

        if form.is_valid():
            pre_device = {}
            for name, data in form.cleaned_data.items():
                if name.startswith(('ip_', 'status_')):
                    info, index = name.split('_')
                    device = pre_device.get(index, {})
                    device[info] = data

                    pre_device[index] = device

            for device in pre_device.values():
                ip = device['ip']
                if device['status'] == 'true':
                    status = True
                else:
                    status = False

                Device.objects.update_or_create(
                    ip_address=ip,
                    defaults={
                        'status': status,
                        'snmp_version': form.cleaned_data['snmp_version'],
                        'snmp_community': form.cleaned_data['snmp_community'],
                        'snmp_username': form.cleaned_data['snmp_username'],
                        'snmp_password': form.cleaned_data['snmp_password']
                    }
                )

        messages.success(request, 'Added devices successfully.')
        return redirect('list-device')

network-monitor-master/network_monitor/discover/templates/discover/add_discover_form.html
<div class="card" id="add-discover">
    <div class="card-header d-flex align-items-center">
        <h3 class="h4">Discover</h3>
    </div>
    <div class="card-body">
        <form method="post" action="{% url 'discover-device' %}">
            {% csrf_token %}
            <input type="hidden" name="add_type" value="discover">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Network</label>
                <div class="col-sm-9"><input name="network" type="text"
                                             placeholder="Ex. 192.168.1.0/24, 192.168.1.0 255.255.255.0"
                                             class="form-control"></div>
                <div class="col-sm-1"><input type="submit" value="Scan" class="btn btn-primary float-right"></div>

            </div>
        </form>
        <div class="card">
            <div class="card-header">
                Scan result
            </div>
            <div class="card-body">
                <form action="{% url 'device-add-discover' %}" method="post">
                    {% csrf_token %}
                    <div class="table-responsive">

                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <div class="custom-control custom-checkbox">
                                        <input @click="selectAll" v-model="allSelected" type="checkbox"
                                               class="custom-control-input"
                                               id="addAll">
                                        <label class="custom-control-label" for="addAll">Select all</label>
                                    </div>
                                </th>
                                <th>IP Address</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr v-for="(value, index) in sortResult" v-if="value.status">
                                <th scope="row">
                                    <div class="custom-control custom-checkbox">
                                        <input v-model="selected" :value="value.ip" type="checkbox"
                                               class="custom-control-input" :id="'n' + index">
                                        <label class="custom-control-label" :for="'n' + index">&nbsp;</label>
                                    </div>
                                </th>
                                <td>${value.ip}</td>
                                <td><span class="badge badge-success">Online</span></td>
                                <input type="hidden" :name="'ip_' + index" :value="value.ip"
                                       :disabled="isSelected(value.ip) ? false: true">
                                <input type="hidden" :name="'status_' + index" :value="value.status"
                                       :disabled="isSelected(value.ip) ? false: true">
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-primary float-right" data-toggle="modal"
                                data-target="#confirmAdd">
                            Add
                        </button>

                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="confirmAdd" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% include 'discover/snmp_selector.html' %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

network-monitor-master/network_monitor/discover/templates/discover/add_manual_form.html
<div class="card" id="add-manual">
    <div class="card-header d-flex align-items-center">
        <h3 class="h4">Manual</h3>
    </div>
    <div class="card-body">
        <form method="post" action="{% url 'device-add-manual' %}" class="form-horizontal">
            <input type="hidden" name="add_type" value="manual">
            {% csrf_token %}
            <div class="form-group row">
                <label class="form-control-label col-sm-2">IP</label>
                <div class="col-sm-10">
                    <input name="ip_address" type="text" placeholder="Ex. 192.168.1.1"
                           class="form-control">
                </div>
            </div>
            <div class="line"></div>

            {% include 'discover/snmp_selector.html' %}

            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </div>
        </form>
    </div>
</div>

network-monitor-master/network_monitor/discover/templates/discover/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}Home{% endblock %} - AIT Monitor</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="robots" content="all,follow">
  <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="{% static 'network_monitor/vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome CSS-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css">
  <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.11/lodash.min.js"
          integrity="sha256-7/yoZS3548fXSRXqc/xYzjsmuW3sFKzuvOCHd06Pmps=" crossorigin="anonymous"></script>
  <!-- Fontastic Custom icon font-->
  <link rel="stylesheet" href="{% static 'network_monitor/css/fontastic.css' %}">
  <!-- Google fonts - Poppins -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{% static 'network_monitor/css/style.default.css' %}" id="theme-stylesheet">
  <link rel="stylesheet" href="{% static 'network_monitor/css/flatpickr.min.css' %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'network_monitor/css/custom.css' %}">
  <!-- Favicon-->
  <link rel="shortcut icon" href="{% static 'network_monitor/img/favicon.ico' %}">
  <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
<div class="page">
  <!-- Main Navbar-->
  <header class="header">
    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-holder d-flex align-items-center justify-content-between">
          <!-- Navbar Header-->
          <div class="navbar-header">
            <!-- Navbar Brand --><a href="{% url 'search-device' %}" class="navbar-brand d-none d-sm-inline-block">
            <div class="brand-text d-none d-lg-inline-block"><img width="96" class="img-thumbnail" src="{% static 'network_monitor/icon/logo.png' %}"></div>
            <div class="brand-text d-none d-sm-inline-block d-lg-none"><strong></strong></div>
          </a>
            <!-- Toggle Button--><a id="toggle-btn" href="#"
                                    class="menu-btn active"><span></span><span></span><span></span></a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <div class="page-content d-flex align-items-stretch">
    <!-- Side Navbar -->
    {% block navbar %}{% include 'discover/navbar.html' with active_tab=active_tab %}{% endblock %}
    <div class="content-inner">
      <!-- Page Header-->
      <header class="page-header">
        <div class="container-fluid">
          <h2 class="no-margin-bottom">{% block page_header %}Dashboard{% endblock %}</h2>
        </div>
      </header>
      {% if messages %}
        <section class="dashboard-counts no-padding-bottom no-padding-top">
          <div class="container-fluid" id="message-top">
            <div class="row">
              <div class="col-sm-12">
                {% if messages %}
                  <ul class="messages list-group">
                    {% for message in messages %}
                      <li{% if message.tags %}
                        class="list-group-item list-group-item-{{ message.tags }}"{% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                          Important: {% endif %}
                        {{ message }}
                      </li>
                    {% endfor %}
                  </ul>
                {% endif %}
              </div>
            </div>
          </div>
        </section>
      {% endif %}
      {% block content %}

      {% endblock %}

      <!-- Page Footer-->
      <footer class="main-footer">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6">
              <p>AIT &copy; 2017-2019</p>
            </div>
            <div class="col-sm-6 text-right">
              <p>Design by <a href="https://bootstrapious.com/admin-templates" class="external">Bua Bunpitcha</a>
              </p>
              <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
</div>
{% if debug %}
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
{% else %}
  <script src="https://cdn.jsdelivr.net/npm/vue"></script>
{% endif %}

<!-- JavaScript files-->
<script src="{% static 'network_monitor/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'network_monitor/vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'network_monitor/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'network_monitor/vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'network_monitor/vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'network_monitor/vendor/jquery-validation/jquery.validate.min.js' %}"></script>
<script src="{% static 'network_monitor/js/flatpickr.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.js"></script>
{#<script src="{% static 'network_monitor/js/charts-home.js' %}"></script>#}
<!-- Main File-->
<script src="{% static 'network_monitor/js/front.js' %}"></script>

{% block script %}{% endblock %}
</body>
</html>

network-monitor-master/network_monitor/discover/templates/discover/navbar.html
{% load static %}
<nav class="side-navbar">
  <!-- Sidebar Header-->
  <div class="sidebar-header d-flex align-items-center">
    <div class="avatar"><img src="{% static 'network_monitor/icon/user.png' %}" alt="..."
                             class="img-fluid rounded-circle"></div>
    <div class="title">
      <h1 class="h4">Hello, {{ user.first_name }}</h1>
      <p>{{ user.email }}</p>
    </div>
  </div>
  <!-- Sidebar Navidation Menus-->
  <span class="heading">Main</span>
  <ul class="list-unstyled">
    {% if perms.device.add_device %}
      <li class="{% if active_tab == 'discover' %} active{% endif %}"><a href="{% url 'discover-device' %}"> <i
        class="icon-home"></i>Discover device </a></li>
    {% endif %}
    <li class="{% if active_tab == 'search-device' %} active{% endif %}"><a href="{% url 'search-device' %}"> <i
      class="icon-search"></i>Search device </a></li>
    {% if perms.device.change_device %}
    <li class="{% if active_tab == 'device-list' %} active{% endif %}"><a href="{% url 'list-device' %}"> <i
      class="fa fa-th-list"></i>List device </a></li>
    {% endif %}
    <li class="{% if active_tab == 'device-network' %} active{% endif %}"><a href="{% url 'device-network' %}"> <i
      class="fa fa-desktop"></i>Network device </a></li>
    <li class="{% if active_tab == 'report' %} active{% endif %}"><a href="{% url 'report-index' %}"> <i
      class="fa fa-desktop"></i>Report </a></li>
    {% if user.is_superuser %}
      <li class="{% if active_tab == 'list-task' %} active{% endif %}"><a href="{% url 'list-task' %}"> <i
        class="fa fa-tasks"></i>List of tasks</a></li>
      <li class="{% if active_tab == 'account' %} active{% endif %}"><a href="{% url 'userlist' %}"> <i
        class="fa fa-tasks"></i>User management</a></li>
    {% endif %}
    {% if perms.setting.change_settings %}
      <li class="{% if active_tab == 'setting' %} active{% endif %}"><a href="{% url 'setting-index' %}"> <i
        class="fa fa-cog"></i>Settings</a></li>
    {% endif %}
    <li class=""><a href="{% url 'logout' %}">Logout</a></li>
  </ul>

</nav>

network-monitor-master/network_monitor/discover/templates/discover/snmp_v1_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>